# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'swift-sdk-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-sdk-sample
  pod 'BitmarkSDK', :git => 'https://github.com/bitmark-inc/bitmark-sdk-swift.git', :branch => 'master'

end
